/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClienteIndexRouteImport } from './routes/cliente.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ClienteVeiculosRouteImport } from './routes/cliente.veiculos'
import { Route as ClientePerfilRouteImport } from './routes/cliente.perfil'
import { Route as ClientePagamentosRouteImport } from './routes/cliente.pagamentos'
import { Route as ClienteLocacoesRouteImport } from './routes/cliente.locacoes'
import { Route as ClienteAtendimentoRouteImport } from './routes/cliente.atendimento'
import { Route as AdminVeiculosRouteImport } from './routes/admin.veiculos'
import { Route as AdminPagamentosRouteImport } from './routes/admin.pagamentos'
import { Route as AdminLocacoesRouteImport } from './routes/admin.locacoes'
import { Route as AdminInspecoesRouteImport } from './routes/admin.inspecoes'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminAtendimentosRouteImport } from './routes/admin.atendimentos'
import { Route as AdminAgendamentosRouteImport } from './routes/admin.agendamentos'
import { Route as ClienteAgendamentosIndexRouteImport } from './routes/cliente.agendamentos.index'
import { Route as ClienteVeiculosIdRouteImport } from './routes/cliente.veiculos.$id'
import { Route as ClienteAgendamentosNovoRouteImport } from './routes/cliente.agendamentos.novo'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteIndexRoute = ClienteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClienteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ClienteVeiculosRoute = ClienteVeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => ClienteRoute,
} as any)
const ClientePerfilRoute = ClientePerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => ClienteRoute,
} as any)
const ClientePagamentosRoute = ClientePagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => ClienteRoute,
} as any)
const ClienteLocacoesRoute = ClienteLocacoesRouteImport.update({
  id: '/locacoes',
  path: '/locacoes',
  getParentRoute: () => ClienteRoute,
} as any)
const ClienteAtendimentoRoute = ClienteAtendimentoRouteImport.update({
  id: '/atendimento',
  path: '/atendimento',
  getParentRoute: () => ClienteRoute,
} as any)
const AdminVeiculosRoute = AdminVeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagamentosRoute = AdminPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocacoesRoute = AdminLocacoesRouteImport.update({
  id: '/locacoes',
  path: '/locacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInspecoesRoute = AdminInspecoesRouteImport.update({
  id: '/inspecoes',
  path: '/inspecoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAtendimentosRoute = AdminAtendimentosRouteImport.update({
  id: '/atendimentos',
  path: '/atendimentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgendamentosRoute = AdminAgendamentosRouteImport.update({
  id: '/agendamentos',
  path: '/agendamentos',
  getParentRoute: () => AdminRoute,
} as any)
const ClienteAgendamentosIndexRoute =
  ClienteAgendamentosIndexRouteImport.update({
    id: '/agendamentos/',
    path: '/agendamentos/',
    getParentRoute: () => ClienteRoute,
  } as any)
const ClienteVeiculosIdRoute = ClienteVeiculosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClienteVeiculosRoute,
} as any)
const ClienteAgendamentosNovoRoute = ClienteAgendamentosNovoRouteImport.update({
  id: '/agendamentos/novo',
  path: '/agendamentos/novo',
  getParentRoute: () => ClienteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cliente': typeof ClienteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/agendamentos': typeof AdminAgendamentosRoute
  '/admin/atendimentos': typeof AdminAtendimentosRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/inspecoes': typeof AdminInspecoesRoute
  '/admin/locacoes': typeof AdminLocacoesRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/veiculos': typeof AdminVeiculosRoute
  '/cliente/atendimento': typeof ClienteAtendimentoRoute
  '/cliente/locacoes': typeof ClienteLocacoesRoute
  '/cliente/pagamentos': typeof ClientePagamentosRoute
  '/cliente/perfil': typeof ClientePerfilRoute
  '/cliente/veiculos': typeof ClienteVeiculosRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/cliente/': typeof ClienteIndexRoute
  '/cliente/agendamentos/novo': typeof ClienteAgendamentosNovoRoute
  '/cliente/veiculos/$id': typeof ClienteVeiculosIdRoute
  '/cliente/agendamentos/': typeof ClienteAgendamentosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/agendamentos': typeof AdminAgendamentosRoute
  '/admin/atendimentos': typeof AdminAtendimentosRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/inspecoes': typeof AdminInspecoesRoute
  '/admin/locacoes': typeof AdminLocacoesRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/veiculos': typeof AdminVeiculosRoute
  '/cliente/atendimento': typeof ClienteAtendimentoRoute
  '/cliente/locacoes': typeof ClienteLocacoesRoute
  '/cliente/pagamentos': typeof ClientePagamentosRoute
  '/cliente/perfil': typeof ClientePerfilRoute
  '/cliente/veiculos': typeof ClienteVeiculosRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/cliente': typeof ClienteIndexRoute
  '/cliente/agendamentos/novo': typeof ClienteAgendamentosNovoRoute
  '/cliente/veiculos/$id': typeof ClienteVeiculosIdRoute
  '/cliente/agendamentos': typeof ClienteAgendamentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cliente': typeof ClienteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/agendamentos': typeof AdminAgendamentosRoute
  '/admin/atendimentos': typeof AdminAtendimentosRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/inspecoes': typeof AdminInspecoesRoute
  '/admin/locacoes': typeof AdminLocacoesRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/veiculos': typeof AdminVeiculosRoute
  '/cliente/atendimento': typeof ClienteAtendimentoRoute
  '/cliente/locacoes': typeof ClienteLocacoesRoute
  '/cliente/pagamentos': typeof ClientePagamentosRoute
  '/cliente/perfil': typeof ClientePerfilRoute
  '/cliente/veiculos': typeof ClienteVeiculosRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/cliente/': typeof ClienteIndexRoute
  '/cliente/agendamentos/novo': typeof ClienteAgendamentosNovoRoute
  '/cliente/veiculos/$id': typeof ClienteVeiculosIdRoute
  '/cliente/agendamentos/': typeof ClienteAgendamentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cliente'
    | '/login'
    | '/admin/agendamentos'
    | '/admin/atendimentos'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/inspecoes'
    | '/admin/locacoes'
    | '/admin/pagamentos'
    | '/admin/veiculos'
    | '/cliente/atendimento'
    | '/cliente/locacoes'
    | '/cliente/pagamentos'
    | '/cliente/perfil'
    | '/cliente/veiculos'
    | '/admin/'
    | '/cliente/'
    | '/cliente/agendamentos/novo'
    | '/cliente/veiculos/$id'
    | '/cliente/agendamentos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/agendamentos'
    | '/admin/atendimentos'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/inspecoes'
    | '/admin/locacoes'
    | '/admin/pagamentos'
    | '/admin/veiculos'
    | '/cliente/atendimento'
    | '/cliente/locacoes'
    | '/cliente/pagamentos'
    | '/cliente/perfil'
    | '/cliente/veiculos'
    | '/admin'
    | '/cliente'
    | '/cliente/agendamentos/novo'
    | '/cliente/veiculos/$id'
    | '/cliente/agendamentos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cliente'
    | '/login'
    | '/admin/agendamentos'
    | '/admin/atendimentos'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/inspecoes'
    | '/admin/locacoes'
    | '/admin/pagamentos'
    | '/admin/veiculos'
    | '/cliente/atendimento'
    | '/cliente/locacoes'
    | '/cliente/pagamentos'
    | '/cliente/perfil'
    | '/cliente/veiculos'
    | '/admin/'
    | '/cliente/'
    | '/cliente/agendamentos/novo'
    | '/cliente/veiculos/$id'
    | '/cliente/agendamentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClienteRoute: typeof ClienteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/': {
      id: '/cliente/'
      path: '/'
      fullPath: '/cliente/'
      preLoaderRoute: typeof ClienteIndexRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/cliente/veiculos': {
      id: '/cliente/veiculos'
      path: '/veiculos'
      fullPath: '/cliente/veiculos'
      preLoaderRoute: typeof ClienteVeiculosRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/perfil': {
      id: '/cliente/perfil'
      path: '/perfil'
      fullPath: '/cliente/perfil'
      preLoaderRoute: typeof ClientePerfilRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/pagamentos': {
      id: '/cliente/pagamentos'
      path: '/pagamentos'
      fullPath: '/cliente/pagamentos'
      preLoaderRoute: typeof ClientePagamentosRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/locacoes': {
      id: '/cliente/locacoes'
      path: '/locacoes'
      fullPath: '/cliente/locacoes'
      preLoaderRoute: typeof ClienteLocacoesRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/atendimento': {
      id: '/cliente/atendimento'
      path: '/atendimento'
      fullPath: '/cliente/atendimento'
      preLoaderRoute: typeof ClienteAtendimentoRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/admin/veiculos': {
      id: '/admin/veiculos'
      path: '/veiculos'
      fullPath: '/admin/veiculos'
      preLoaderRoute: typeof AdminVeiculosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pagamentos': {
      id: '/admin/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/pagamentos'
      preLoaderRoute: typeof AdminPagamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/locacoes': {
      id: '/admin/locacoes'
      path: '/locacoes'
      fullPath: '/admin/locacoes'
      preLoaderRoute: typeof AdminLocacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inspecoes': {
      id: '/admin/inspecoes'
      path: '/inspecoes'
      fullPath: '/admin/inspecoes'
      preLoaderRoute: typeof AdminInspecoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/atendimentos': {
      id: '/admin/atendimentos'
      path: '/atendimentos'
      fullPath: '/admin/atendimentos'
      preLoaderRoute: typeof AdminAtendimentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agendamentos': {
      id: '/admin/agendamentos'
      path: '/agendamentos'
      fullPath: '/admin/agendamentos'
      preLoaderRoute: typeof AdminAgendamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/cliente/agendamentos/': {
      id: '/cliente/agendamentos/'
      path: '/agendamentos'
      fullPath: '/cliente/agendamentos/'
      preLoaderRoute: typeof ClienteAgendamentosIndexRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/veiculos/$id': {
      id: '/cliente/veiculos/$id'
      path: '/$id'
      fullPath: '/cliente/veiculos/$id'
      preLoaderRoute: typeof ClienteVeiculosIdRouteImport
      parentRoute: typeof ClienteVeiculosRoute
    }
    '/cliente/agendamentos/novo': {
      id: '/cliente/agendamentos/novo'
      path: '/agendamentos/novo'
      fullPath: '/cliente/agendamentos/novo'
      preLoaderRoute: typeof ClienteAgendamentosNovoRouteImport
      parentRoute: typeof ClienteRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAgendamentosRoute: typeof AdminAgendamentosRoute
  AdminAtendimentosRoute: typeof AdminAtendimentosRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminInspecoesRoute: typeof AdminInspecoesRoute
  AdminLocacoesRoute: typeof AdminLocacoesRoute
  AdminPagamentosRoute: typeof AdminPagamentosRoute
  AdminVeiculosRoute: typeof AdminVeiculosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgendamentosRoute: AdminAgendamentosRoute,
  AdminAtendimentosRoute: AdminAtendimentosRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminInspecoesRoute: AdminInspecoesRoute,
  AdminLocacoesRoute: AdminLocacoesRoute,
  AdminPagamentosRoute: AdminPagamentosRoute,
  AdminVeiculosRoute: AdminVeiculosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClienteVeiculosRouteChildren {
  ClienteVeiculosIdRoute: typeof ClienteVeiculosIdRoute
}

const ClienteVeiculosRouteChildren: ClienteVeiculosRouteChildren = {
  ClienteVeiculosIdRoute: ClienteVeiculosIdRoute,
}

const ClienteVeiculosRouteWithChildren = ClienteVeiculosRoute._addFileChildren(
  ClienteVeiculosRouteChildren,
)

interface ClienteRouteChildren {
  ClienteAtendimentoRoute: typeof ClienteAtendimentoRoute
  ClienteLocacoesRoute: typeof ClienteLocacoesRoute
  ClientePagamentosRoute: typeof ClientePagamentosRoute
  ClientePerfilRoute: typeof ClientePerfilRoute
  ClienteVeiculosRoute: typeof ClienteVeiculosRouteWithChildren
  ClienteIndexRoute: typeof ClienteIndexRoute
  ClienteAgendamentosNovoRoute: typeof ClienteAgendamentosNovoRoute
  ClienteAgendamentosIndexRoute: typeof ClienteAgendamentosIndexRoute
}

const ClienteRouteChildren: ClienteRouteChildren = {
  ClienteAtendimentoRoute: ClienteAtendimentoRoute,
  ClienteLocacoesRoute: ClienteLocacoesRoute,
  ClientePagamentosRoute: ClientePagamentosRoute,
  ClientePerfilRoute: ClientePerfilRoute,
  ClienteVeiculosRoute: ClienteVeiculosRouteWithChildren,
  ClienteIndexRoute: ClienteIndexRoute,
  ClienteAgendamentosNovoRoute: ClienteAgendamentosNovoRoute,
  ClienteAgendamentosIndexRoute: ClienteAgendamentosIndexRoute,
}

const ClienteRouteWithChildren =
  ClienteRoute._addFileChildren(ClienteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ClienteRoute: ClienteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
